// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxbP_dMN-weJv9snrlTuQYXrmt1LLFwdY',
    appId: '1:52000202988:web:ae28345949cb7fae2cc5c9',
    messagingSenderId: '52000202988',
    projectId: 'fluxter-4435d',
    authDomain: 'fluxter-4435d.firebaseapp.com',
    storageBucket: 'fluxter-4435d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASR-VVOGIMzwMjT_sB5NglsmjSEb-yNTU',
    appId: '1:52000202988:android:10127f63ac80ea792cc5c9',
    messagingSenderId: '52000202988',
    projectId: 'fluxter-4435d',
    storageBucket: 'fluxter-4435d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0AqjXNYhXJ2KUOk2tgrtJj1B0Z0zO4pc',
    appId: '1:52000202988:ios:41db18987bc299f62cc5c9',
    messagingSenderId: '52000202988',
    projectId: 'fluxter-4435d',
    storageBucket: 'fluxter-4435d.appspot.com',
    iosBundleId: 'com.example.fluxter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0AqjXNYhXJ2KUOk2tgrtJj1B0Z0zO4pc',
    appId: '1:52000202988:ios:c430487ce988d48d2cc5c9',
    messagingSenderId: '52000202988',
    projectId: 'fluxter-4435d',
    storageBucket: 'fluxter-4435d.appspot.com',
    iosBundleId: 'com.example.fluxter.RunnerTests',
  );
}
